site_name: import idea
site_author: Akash Desarda
theme:
  name: "material"
  palette:
    scheme: preference
    primary: deep orange
    accent: green
    features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - toc.integrate
extra:
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:desardaakash@gmail.com
      name: Contact me
    - icon: fontawesome/brands/github
      link: https://github.com/Akashdesarda
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/akashdesarda/
    - icon: fontawesome/brands/medium
      link: https://www.medium.com/@desardaakash
plugins:
  - search
  - tags:
      # tags_folder: docs
markdown_extensions:
  - meta
  - attr_list
  - admonition
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.smartsymbols
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde

nav:
  - Home: index.md
  - Articles:
    - Programming: programming.md
    - Tools: tools.md
    - Miscellaneous: misc.md
    - Category: 
      - Tags: tags.md
      - Author: author_tags.md
  - About: about.md
