site_name: import idea
theme:
  name: "material"
  palette:
    scheme: preference
    primary: deep orange
    accent: green
    features:
    # - tabs: true
    - navigation.instant
    - navigation.tabs
    - navigation.sections
extra:
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:desardaakash@gmail.com
      name: Contact me
    - icon: fontawesome/brands/github
      link: https://github.com/Akashdesarda
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/akashdesarda/
    - icon: fontawesome/brands/medium
      link: https://www.medium.com/@desardaakash
plugins:
  - search
  - tags:
      tags_folder: docs
markdown_extensions:
  - meta
nav:
  - Home: index.md
  - Programming:
    - Programming: programming.md
  - Tools:
    - Tools: tools.md
  - Miscellaneous:
    - Miscellaneous: misc.md
  - Category: tags.md
  - About: about.md